version: '3.5'
services:
  php:
    build:
      context: ./.docker/php
      args:
        uid: ${UID}
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    ports:
      - "8000:80"
    networks:
      default:
        aliases:
          - "default"

  mysql:
    image: mysql:5.7
    volumes:
      - .docker/mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=default
    networks:
      default:
        aliases:
          - "default"

networks:
  default:
    name: backend-network